# Generated by Django 5.0.3 on 2024-04-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_event_type_event_online_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='online_location',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10),
        ),
    ]
