# Generated by Django 5.0.3 on 2024-04-23 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_response_event_attendee_responses_delete_rsvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendee_responses',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
