# Generated by Django 5.0.3 on 2024-05-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('personal', 'Personal'), ('social', 'Social'), ('holiday', 'Holiday'), ('education', 'Education')], max_length=20, null=True),
        ),
    ]
